=== radiopurity/persephone/_attachments/schema/v2.01.schema.json
{
	"description": "", 
	"title": "AARM database data document schema", 
	"additionalProperties": false, 
	"$schema": "http://json-schema.org/draft-03/schema#",
	"required": false, 
	"type": "object", 
	"properties": {
		"sample": {
			"additionalProperties": false, 
			"required": true, 
			"type": "object", 
			"properties": {
				"user":{"$ref":"#user_def"},
				"id": { "required": false,	"type": "string",	"title": "Identification number" }, 
				"owner": {"$ref":"#contact_def"}, 
				"description": { "required": false,	"type": "string",	"title": "detailed description"}, 
				"source": {"required": false,	"type": "string",	"title": "where the sample came from"}, 
				"name": { "required": true,	"type": "string",	"title": "short description" }
				}
		}, 
		"data_source": {
			"additionalProperties": false, 
			"required": true, 
			"type": "object",
			"properties": {
				"user":{"$ref":"#user_def"},
				"notes": {"required": false,	"type": "string", "title": "Comments on issues with data entry"}, 
				"input": {
					"required": true, 
					"type": "object", 
					"extends":{"$ref":"#contact_def"},
					"properties": {
						"date": {
							"pattern":"^[\t ]*|((18|19|20)[0-9]{2}-(1[0-2]|0[1-9])-(0[1-9]|[12][0-9]|3[01]))$",
							"required": true, 
							"type": "string", 
							"description": "must be in the form of YYYY-MM-DD", 
							"title": "creation date of this document"
							}
						}
					}, 
				"reference": {"required": true,	"type": "string", "title": "A reference to data source, such as a publication"}
				}
		}, 
		"sort_indices":{
			"additionalProperties": false, 
			"required": false, 
			"type": "object",
			"properties": {
				"u": { 
					"required": false,
					"type": "number", 
					"title": "uranium sorting indice"
				}, 
				"th": { 
					"required": false,
					"type": "number", 
					"title": "thorium sorting indice"
				}
			}
		},
		"measurement": {
			"additionalProperties": false, 
			"required": true, 
			"type": "object",
			"properties": {
				"user":{"$ref":"#user_def"},
				"requestor": { "$ref":"#contact_def", "title": "Responsible for commissioning/managing/funding of measurement"}, 
				"results": {
					"uniqueItems": true, 
					"additionalItems": false, 
					"title": "A list of results", 
					"minItems": 0, 
					"items": {
						"type": "object", 
						"properties": {
							"type": { "required": true, "type": "string"}, 
							"value":{"$ref":"#value_def"},
							"unit": {
								"pattern": "pct|ppm|ppb|ppt|ppq|Bq/kg|mBq/kg|uBq/kg|\u00B5Bq/kg|nBq/kg|mBq|muBq/m|pg/cm|ng/cm2", 
								"required": true, 
								"type": "string"
								}, 
							"isotope": {
								"pattern": "[A-Z][a-z]{0,1}-[0-9]{0,3}|[A-Z][a-z]{0,1}", 
								"required": true, 
								"type": "string"
								}
							}
						}, 
					"required": true, 
					"type": "array"
					}, 
				"practitioner": { "$ref":"#contact_def", "title": "Person responsible for the measurement"}, 
				"technique": {"required": false, "type": "string"}, 
				"date": {
					"minItems": 0,
					"items": {
						"pattern":"^[\t ]*|((18|19|20)[0-9]{2}-(1[0-2]|0[1-9])-(0[1-9]|[12][0-9]|3[01]))|((18|19|20)[0-9]{2}-(1[0-2]|0[1-9]))|((18|19|20)[0-9]{2})$",
						"type":"string"
						}, 
					"required": false, 
					"maxItems": 2, 
					"uniqueItems": false, 
					"additionalItems":false,
					"type": "array"
				},
				"institution": { "required": false, "type": "string",	"title": "Name of Institution where measurement was made"}, 
				"description": {"required": false, "type": "string", "title": "Detailed description of the procedures for data acquisition and analysis"}
				}
			}, 
		"_rev": { "required": false,	"type": "string", 
			"description": "this is NOT required since it is not required to upload the document to couchdb", 
			"title": "couchdb _rev document revision number"
			}, 
		"_id": { "required": false,	 "type": "string", 
			"description": "this is NOT required since it is not required to upload the document to couchdb", 
			"title": "couchdb _id document identifier"
			}, 
		"type": { "required": true, "enum": ["measurement"], "title": "Must be set to measurement"}, 
		"user":{"$ref":"#user_def"},
		"specification": { "required": true, "enum": ["2.01","2.02"],
			"description": "must be set to '2.01' (a string)", 
			"title": "The version number of the specification"
			}, 
		"grouping": { "required": true, "type": "string", 
			"description": "Usually this will be the name of the experiment or collaboration that made the measurement", 
			"title": "The group to which the document belongs"
			}
		},
	"value_def":{
		"title": "Values expressing a measurement, range or limit", 
		"minItems": 0, 
		"items": {
			"type": "number"
			}, 
		"required": true, 
		"maxItems": 3, 
		"uniqueItems": false, 
		"type": "array"
		},
	"contact_def":{
		"required": false, 
		"type": "object", 
		"properties": {
			"contact": {
				"required": true, 
				"type": "string", 
				"title": "Institution or email/postal address"
				}, 
			"name": {
				"required": true, 
				"type": "string" 
				}
			}
		},
	"user_def" : {
		"type":"array",
		"required":false,
		"items":{
			"type":[
					{
						"type":"object",
						"properties":{
							"name":{ "required":true, "type":"string"},
							"description":{ "required":false, "type":"string"},
							"type":{ "required": true, 
								"enum": ["string"]
								},
							"value":{ "required":true,	"type":"string"}
							}
						},
					{
						"type":"object",
						"properties":{
							"name":{ "required":true, "type":"string"},
							"description":{ "required":false, "type":"string"},
							"type":{ "required": true, 
								"enum": ["measurement", "range", "limit"]
								},
							"value":{"$ref":"#value_def"},
							"unit":{ "required":true, "type":"string",
								"title":"A unit for the measured values"
								}
							}
						}
				]
			},
		"title":"User-allowed extension"
	}
}

=== radiopurity/persephone/doc/data_specification/example_assays/example_v2.01_user.json
{

  "type":                   "measurement",

  "grouping":               "0vBB Experiment",

  "sample": {
    "name":                 "Plombum, VG2 lead",
    "description":          "Plombum, VG2 lead, lot #D9119",
    "id":                   "Pb-001",
    "source":               "Plombum FL",
    "owner": { 
      "name":                   "Alice Professor, A University", 
      "contact":                "alice@university.edu" 
    }
  },

  "measurement": {
    "institution":          "Low-background Facility",
    "technique":            "Gamma",
    "date":                 ["2000-05-02", "2000-05-09"],
    "requestor": { 
      "name":                   "Alice Professor, A University", 
      "contact":                "alice@university.edu" 
    },
    "practitioner": { 
      "name":                   "Bob Technician", 
      "contact":                "bob@lowbackground.edu" 
    },
    "description":          "Standard gamma count of the whole brick.", 
    "results": [
      { "isotope":"Th-232", "type":"limit",       "value":[3.3],    "unit":"ppb" },
      { "isotope":"U-238",  "type":"limit",       "value":[19],     "unit":"ppb" },
      { "isotope":"K",      "type":"measurement", "value":[170,30], "unit":"ppt" }
    ]
  },

  "data_source": {
    "reference":            "0vBB-EXP-0004 (Technical report)",
    "input": { 
      "name":                   "Eve Undergraduate", 
      "contact":                "eve@university.edu",
      "date":                   "2010-01-01"                
    },
    "notes":                "There seems to be a typo in the results list in the report. Interperate U-239 as U-238."    
  },

  "user": [ {
      "name":        "Data file",
      "description": ".spe data file",
      "type":        "string",
      "value":       "2010-A-0092.spe"
  } ],

  "specification":          "2.01"

}
